<?php

declare(strict_types=1);
$site=require __DIR__.'/config.php';require __DIR__.'/includes/content.php';require __DIR__.'/includes/layout.php';
$slug=(string)($_GET['slug']??'');$service=content_by_slug('services',$slug);if(!$service){http_response_code(404);$service=['title'=>'Услуга не найдена','summary'=>'Проверьте адрес или вернитесь в каталог.','body'=>'','price'=>'','duration'=>'','category'=>''];}
$serviceTitle=trim((string)($service['seo_title']??''));if($serviceTitle==='')$serviceTitle=page_title($site,(string)$service['title']);
$serviceDesc=trim((string)($service['meta_description']??''));if($serviceDesc==='')$serviceDesc=(string)$service['summary'];
$seoOverride=['title'=>$serviceTitle,'description'=>$serviceDesc,'og_image'=>(string)($service['og_image']??media_cover($service,'services'))];$booking=site_booking_href($site);
render_header($site,'services',(string)$service['title'],(string)$service['summary'],$seoOverride);render_page_hero('Услуги',esc((string)$service['title']),(string)$service['summary']);
?>
<main><section class="section"><div class="container content-shell"><article class="prose reveal"><div class="media-cover detail-cover"><img src="<?=esc(media_cover($service,'services'))?>" alt="<?=esc(media_alt($service,(string)$service['title']))?>"></div><p class="kicker"><?=esc((string)$service['category'])?></p><?=render_text((string)$service['body'])?><h2>Как принимается решение</h2><p>Перед процедурой уточняются запрос, состояние кожи, домашний уход и возможные ограничения. Конкретный протокол может отличаться от демонстрационного описания на сайте.</p><h2>После процедуры</h2><p>Рекомендации по домашнему уходу и ограничениям зависят от выбранного протокола. Они должны быть понятными и выполнимыми — без лишней перегрузки средствами.</p></article><aside><div class="sidebar-card reveal"><p class="kicker">Коротко</p><h3><?=esc((string)$service['title'])?></h3><p><?=esc((string)$service['duration'])?></p><p><strong><?=esc((string)$service['price'])?></strong></p><a class="button button-dark button-full" href="<?=esc($booking)?>">Записаться</a><a class="button button-outline button-full" style="margin-top:8px" href="/price.php">Смотреть прайс</a></div></aside></div></section></main><?php render_footer($site);?>